import { escapeHtml } from './ui.js';

type DateValue = Date | string | null;
type Rule = { id: number; name: string; enabled: boolean; actionKeys?: string[]; triggerKey: string; triggerConfig: Record<string, unknown>; timezone: string; nextRunAt: DateValue; configVersion: number; updatedAt: Date | string };
type Execution = { id: string; automationId: number; automationName: string; triggerKey: string; status: string; attempts: number; createdAt: Date | string; completedAt: DateValue; safeErrorCode: string | null; configVersion: number; moduleEpoch: number };
export type AutomationDashboardView = {
  moduleEnabled: boolean;
  channels: { id: string; name: string }[];
  rules: Rule[];
  selected?: Rule & { triggerVersion: number; cooldownSeconds: number; authorizedBy: string; actions: { position: number; actionKey: string; actionVersion: number; config: Record<string, unknown> }[] } | null;
  executions: Execution[];
  selectedExecution?: Execution & { actions: readonly { position: number; actionKey: string; actionVersion: number; status: string; attempts: number; discordMessageId: string | null; safeErrorCode: string | null; updatedAt: DateValue; reconciliationResult: string | null; reconciledBy: string | null; reconciledAt: DateValue }[]; reconciliation: readonly { position: number; allowSent: boolean; allowNotSent: boolean }[] } | null;
};

const h = escapeHtml;
const utc = (value: DateValue): string => {
  if (!value) return '—';
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? '—' : date.toISOString();
};
const field = (name: string, label: string, value: unknown = '', extra = ''): string => `<label>${h(label)}<input name="${name}" type="text" value="${h(value)}" ${extra}></label>`;
const hidden = (name: string, value: unknown): string => `<input type="hidden" name="${name}" value="${h(value)}">`;
const options = (name: string, label: string, entries: { value: string; label: string; disabled?: boolean }[], selected: string): string => `<label>${h(label)}<select name="${name}">${entries.map(({ value, label: title, disabled }) => `<option value="${h(value)}"${value === selected ? ' selected' : ''}${disabled ? ' disabled' : ''}>${h(title)}</option>`).join('')}</select></label>`;
const actionTypes = ['NONE', 'STATIC_MESSAGE', 'STAFF_LOG'];
const configString = (config: Record<string, unknown> | undefined, key: string): string => typeof config?.[key] === 'string' ? String(config[key]) : '';
const scheduleSummary = (config: Record<string, unknown>, timezone: string): string =>
  configString(config, 'kind') === 'once' ? `Once ${configString(config, 'at')} UTC` :
    `Daily ${configString(config, 'time')} ${timezone}`;

export function renderAutomationDashboard({ guildId, csrfToken, data }: { guildId: string; csrfToken: string; data: AutomationDashboardView }): string {
  const base = `/g/${encodeURIComponent(guildId)}`;
  const channels = data.channels.slice(0, 500);
  const channelName = (id: string): string => channels.find((channel) => channel.id === id) ? `#${channels.find((channel) => channel.id === id)!.name}` : id;
  const channelOptions = (selected: string): { value: string; label: string; disabled?: boolean }[] => [{ value: '', label: 'Select a channel' }, ...channels.map(({ id, name }) => ({ value: id, label: `#${name}` })), ...(selected && !channels.some(({ id }) => id === selected) ? [{ value: selected, label: `${selected} (currently unavailable; select another channel)`, disabled: true }] : [])];
  const form = (route: string, label: string, body: string, confirmation = false): string => `<form method="post" action="${h(`${base}/action/${route}`)}"><h3>${h(label)}</h3>${hidden('csrfToken', csrfToken)}${body}${confirmation ? '<label class="check"><input type="checkbox" name="confirm" value="yes" required> I confirm this action</label>' : ''}<button type="submit">${h(label)}</button></form>`;
  const selected = data.selected;
  const actionFields = (index: number): string => {
    const action = selected?.actions.find((item) => item.position === index);
    const config = action?.config;
    const type = action?.actionKey ?? (index === 0 ? 'STATIC_MESSAGE' : 'NONE');
    const channel = configString(config, 'channelId');
    const message = configString(config, 'message');
    return `<fieldset><legend>Action ${index + 1}</legend>${options(`action${index}Type`, 'Action type', actionTypes.filter((item) => index === 1 || item !== 'NONE').map((value) => ({ value, label: value.replace('_', ' ') })), type)}${options(`action${index}ChannelId`, 'Channel', channelOptions(channel), channel)}<label>Message<textarea name="action${index}Message" maxlength="1000" rows="4">${h(message)}</textarea></label></fieldset>`;
  };
  const schedule = selected?.triggerConfig ?? {};
  const scheduleKind = configString(schedule, 'kind') || 'daily';
  const commonFields = `${field('name', 'Name', selected?.name ?? '', 'maxlength="80" required')}${options('scheduleKind', 'Schedule', [{ value: 'daily', label: 'Daily' }, { value: 'once', label: 'Once' }], scheduleKind)}${field('dailyTime', 'Daily time (HH:MM)', configString(schedule, 'time'), 'pattern="([01][0-9]|2[0-3]):[0-5][0-9]" placeholder="09:00"')}${field('onceAt', 'Once at (UTC ISO timestamp ending Z)', configString(schedule, 'at'), 'placeholder="2027-01-01T09:00:00.000Z"')}${field('timezone', 'IANA timezone', selected?.timezone ?? 'UTC', 'maxlength="64" required')}<label>Cooldown seconds<input type="number" name="cooldownSeconds" min="0" max="86400" step="1" value="${h(selected?.cooldownSeconds ?? 0)}" required></label>${options('enabled', 'Enabled', [{ value: 'true', label: 'Yes' }, { value: 'false', label: 'No' }], String(selected?.enabled ?? false))}${actionFields(0)}${actionFields(1)}`;
  const rules = data.rules.slice(0, 100).map((rule) => `<tr><td>${h(rule.id)}</td><td><a href="${h(`${base}/automations?automationId=${encodeURIComponent(String(rule.id))}`)}">${h(rule.name)}</a></td><td>${h(rule.enabled ? 'Enabled' : 'Disabled')}</td><td>${h(rule.triggerKey)} · ${h(scheduleSummary(rule.triggerConfig, rule.timezone))}</td><td>${h(rule.actionKeys?.slice(0, 2).join(', ') || '—')}</td><td>${h(utc(rule.nextRunAt))}</td><td>${h(rule.configVersion)}</td><td>${h(utc(rule.updatedAt))}</td></tr>`).join('');
  const executions = data.executions.slice(0, 50).map((execution) => `<tr><td><a href="${h(`${base}/automations?executionId=${encodeURIComponent(execution.id)}`)}">${h(execution.id)}</a></td><td>${h(execution.automationName)} #${h(execution.automationId)}</td><td>${h(execution.triggerKey)}</td><td>${h(execution.status)}</td><td>${h(execution.attempts)}</td><td>${h(utc(execution.createdAt))}</td><td>${h(utc(execution.completedAt))}</td><td>${h(execution.safeErrorCode ?? '—')}</td><td>${h(execution.configVersion)} / ${h(execution.moduleEpoch)}</td></tr>`).join('');
  const selectedDetails = selected ? `<section><h2>Selected automation: ${h(selected.name)}</h2><p>${h(selected.enabled ? 'Enabled' : 'Disabled')} · ${h(selected.triggerKey)} · ${h(selected.timezone)} · Next UTC: ${h(utc(selected.nextRunAt))}</p><p>Schedule: ${h(scheduleSummary(schedule, selected.timezone))} · Authorized by: ${h(selected.authorizedBy)} · Configuration version: ${h(selected.configVersion)} · Trigger version: ${h(selected.triggerVersion)}</p><p>Updated UTC: ${h(utc(selected.updatedAt))}</p><ul>${selected.actions.slice(0, 2).map((action) => `<li>Action ${h(action.position + 1)}: ${h(action.actionKey)} (version ${h(action.actionVersion)}) · ${h(channelName(configString(action.config, 'channelId')))} · ${h(configString(action.config, 'message'))}</li>`).join('')}</ul>${form('automation-update', 'Save automation', hidden('automationId', selected.id) + commonFields)}${form(selected.enabled ? 'automation-disable' : 'automation-enable', selected.enabled ? 'Disable automation' : 'Enable automation', hidden('automationId', selected.id), true)}${form('automation-delete', 'Delete automation', hidden('automationId', selected.id), true)}<p><a href="${h(`${base}/automations`)}">Create another automation</a></p></section>` : '';
  const execution = data.selectedExecution;
  const executionDetails = execution ? `<section><h2>Execution ${h(execution.id)} · ${h(execution.automationName)}</h2><p>Status: ${h(execution.status)} · Trigger: ${h(execution.triggerKey)} · Attempts: ${h(execution.attempts)} · Created UTC: ${h(utc(execution.createdAt))} · Completed UTC: ${h(utc(execution.completedAt))}</p><p>Error: ${h(execution.safeErrorCode ?? '—')} · Configuration version: ${h(execution.configVersion)} · Module epoch: ${h(execution.moduleEpoch)}</p>${execution.status === 'UNCERTAIN' || execution.actions.some((action) => action.status === 'UNCERTAIN') ? '<p class="error" role="alert">The bot cannot determine whether Discord accepted this message. It will not resend automatically.</p>' : ''}<div class="table-wrap" role="region" aria-label="Execution actions" tabindex="0"><table><caption>Action status and receipts</caption><thead><tr><th scope="col">Position</th><th scope="col">Action</th><th scope="col">Status</th><th scope="col">Attempts</th><th scope="col">Discord receipt</th><th scope="col">Error</th><th scope="col">Updated UTC</th><th scope="col">Reconciliation</th></tr></thead><tbody>${execution.actions.slice(0, 20).map((action) => `<tr><td>${h(action.position)}</td><td>${h(action.actionKey)} v${h(action.actionVersion)}</td><td>${h(action.status)}</td><td>${h(action.attempts)}</td><td>${h(action.discordMessageId ?? '—')}</td><td>${h(action.safeErrorCode ?? '—')}</td><td>${h(utc(action.updatedAt))}</td><td>${h(action.reconciliationResult ?? '—')} · ${h(action.reconciledBy ?? '—')} · ${h(utc(action.reconciledAt))}</td></tr>`).join('')}</tbody></table></div>${execution.reconciliation.slice(0, 20).flatMap((eligibility) => [eligibility.allowSent ? form('automation-reconcile-sent', `Mark action ${eligibility.position} sent`, hidden('automationId', execution.automationId) + hidden('executionId', execution.id) + hidden('position', eligibility.position), true) : '', eligibility.allowNotSent ? form('automation-reconcile-not-sent', `Mark action ${eligibility.position} not sent`, hidden('automationId', execution.automationId) + hidden('executionId', execution.id) + hidden('position', eligibility.position), true) : '']).join('')}</section>` : '';
  return `<section aria-label="Automations"><p role="status">Automation module: ${h(data.moduleEnabled ? 'Enabled' : 'Disabled')}</p>${!data.moduleEnabled ? '<p class="disabled">The module is disabled: rules and history remain manageable, but no action can dispatch.</p>' : ''}<p class="muted">Only scheduled, administrator-authored static messages are supported. No dynamic content is used.</p>${form('automation-module-toggle', 'Set automation availability', hidden('module', 'automation') + options('enabled', 'Enabled', [{ value: 'true', label: 'Yes' }, { value: 'false', label: 'No' }], String(data.moduleEnabled)), true)}<h2>Rules</h2><div class="table-wrap" role="region" aria-label="Automation rules" tabindex="0"><table><caption>Up to 100 automation rules</caption><thead><tr><th scope="col">ID</th><th scope="col">Name</th><th scope="col">Rule state</th><th scope="col">Schedule</th><th scope="col">Actions</th><th scope="col">Next UTC</th><th scope="col">Version</th><th scope="col">Updated UTC</th></tr></thead><tbody>${rules}</tbody></table></div>${!rules ? '<p class="empty">No automation rules yet.</p>' : ''}${selectedDetails}${!selected ? form('automation-create', 'Create automation', commonFields) : ''}<h2>Executions</h2><div class="table-wrap" role="region" aria-label="Automation executions" tabindex="0"><table><caption>Up to 50 recent executions</caption><thead><tr><th scope="col">Execution ID</th><th scope="col">Automation</th><th scope="col">Trigger</th><th scope="col">Status</th><th scope="col">Attempts</th><th scope="col">Created UTC</th><th scope="col">Completed UTC</th><th scope="col">Error</th><th scope="col">Config / module epoch</th></tr></thead><tbody>${executions}</tbody></table></div>${!executions ? '<p class="empty">No executions yet.</p>' : ''}${executionDetails}</section>`;
}
