import type { OperationsDashboardView } from '../services/operations-view.js';
import type { SchedulerTelemetrySnapshot } from '../core/operations/scheduler-telemetry.js';
import { escapeHtml as e, utc, tableShell, statusBadge, notice, emptyState } from './presentation.js';

const table = (caption: string, columns: readonly string[], rows: readonly (readonly unknown[])[]): string => tableShell(caption, columns, rows.map(row => [...row]), { statusColumns: columns.flatMap((column, index) => ['State', 'Effective state', 'Classification'].includes(column) ? [index] : []) }) + (!rows.length ? emptyState(`No entries: ${caption}.`, 'No evidence is listed in this selected view; absence does not prove health.') : '');
function scheduler(name: string, value: SchedulerTelemetrySnapshot): string {
  return `<section class="panel"><h3>${e(name)} — ${statusBadge(value.state)}</h3><p>Since process restart. Ticks attempted: ${e(value.tickCount)}; active tick: ${statusBadge(value.running ? 'RUNNING' : 'IDLE')}. Started: ${e(utc(value.startedAt))}; stopped: ${e(utc(value.stoppedAt))}. Last tick started: ${e(utc(value.lastTickStartedAt))}; completed: ${e(utc(value.lastTickCompletedAt))}; active since: ${e(utc(value.activeTickStartedAt))}.</p>${table('Job telemetry — Since process restart', ['Job', 'State', 'Last attempt (UTC)', 'Last success (UTC)', 'Last failure (UTC)', 'Duration (ms)', 'Running since (UTC)', 'Failure category', 'Static stage'], value.jobs.map(job => [job.name, job.state, utc(job.lastAttemptAt), utc(job.lastSuccessAt), utc(job.lastFailureAt), job.lastDurationMs ?? '—', utc(job.currentRunningSince), job.lastFailureCategory ?? '—', job.stage ?? '—']))}</section>`;
}
export function renderOperationsDashboard(guildId: string, data: OperationsDashboardView): string {
  const { process: processState, readiness, guild } = data;
  const processRows: unknown[][] = [
    ['Process phase', processState.phase], ['Process started (UTC)', utc(processState.processStartedAt)],
    ['Process uptime (seconds, process clock)', Math.floor(processState.uptimeMs / 1000)],
    ['Startup schema probe', processState.startupProbe], ['Startup failure category', processState.startupProbeFailureCategory ?? '—'],
    ['Readiness', readiness.ready ? 'READY' : 'NOT_READY'], ['Database', readiness.database], ['Migrations', readiness.migrations],
    ['Expected migration count', readiness.expectedCount], ['Observed migration count', readiness.observedCount ?? 'UNAVAILABLE'],
    ['Expected latest migration tag', readiness.expectedTag], ['Observed latest migration tag', readiness.observedTag ?? 'UNAVAILABLE'],
    ['Discord gateway', readiness.gateway], ['Scheduler freshness', readiness.scheduler],
  ];
  for (const [name, value] of Object.entries(processState.reconciliations)) processRows.push([`${name} startup reconciliation`, value.status], [`${name} safe failure category`, value.failureCategory ?? '—']);
  const statusFields = new Set(['Process phase', 'Startup schema probe', 'Readiness', 'Database', 'Migrations', 'Discord gateway', 'Scheduler freshness']);
  const processTable = `<div class="table-wrap" role="region" aria-label="Global process metadata (process clock)" tabindex="0"><table><caption>Global process metadata (process clock)</caption><thead><tr><th scope="col">Field</th><th scope="col">State</th></tr></thead><tbody>${processRows.map(([label, value]) => `<tr><th scope="row">${e(label)}</th><td>${statusFields.has(String(label)) || String(label).endsWith(' startup reconciliation') ? statusBadge(value) : e(value)}</td></tr>`).join('')}</tbody></table></div>`;
  const base = `/g/${encodeURIComponent(guildId)}`;
  const boundaryLabels: Partial<Record<string, string>> = { backup_health: 'Production backup health',
    discord_orphans: 'Actual Discord ticket-channel orphan state', tls_health: 'External TLS / reverse-proxy health',
    historical_failures: 'Scheduler failures before current process restart' };
  return `<section class="panel"><h2>Process / readiness</h2>${notice('Runtime telemetry since process restart. No durable history; an absence of errors does not prove historic health.', 'INFO', 'Since process restart')}<p>Readiness: ${statusBadge(readiness.ready ? 'READY' : 'NOT_READY')} · Process phase: ${statusBadge(processState.phase)}</p>${processTable}</section>
<section class="panel"><h2>Scheduler status — Since process restart</h2><p>Freshness requires a completed tick within max(3 × interval, 90 seconds), with no active tick exceeding that threshold. A failed individual job is DEGRADED; fresh ticks alone do not prove every job succeeded.</p>${scheduler('V5 scheduler', data.schedulers.v5)}${scheduler('Moderation scheduler', data.schedulers.moderation)}</section>
<section class="panel"><h2>Guild modules</h2><p>Effective availability and persisted state epoch/version; not an application release version. Core is always enabled. No override means epoch 0.</p>${guild.modules === null ? notice('UNAVAILABLE: guild module state could not be read. This is not an enabled or healthy state.', 'WARNING') : table('Selected guild only', ['Module key', 'Effective state', 'Epoch/version'], guild.modules.map(m => [m.key, m.enabled ? 'ENABLED' : 'DISABLED', m.version]))}</section>
<section class="panel"><h2>Guild operational backlog</h2><p>Read-only durable evidence for this guild only. Ages use PostgreSQL time, not browser time. Pending work may be awaiting the next normal tick; fresh claims are not failures.</p>${table('Guild-scoped counts and database ages', ['Diagnostic', 'Classification', 'Count', 'Oldest relevant timestamp (UTC)', 'Age (seconds, DB clock)'], guild.diagnostics.filter(d => d.status !== 'NOT_TRACKED').map(d => [d.key, d.status, d.count ?? 'UNAVAILABLE', utc(d.oldestAt), d.ageSeconds ?? '—']))}</section>
<section class="panel"><h2>Governance warnings / existing reconciliation links</h2>${notice('Automation UNCERTAIN: The external side effect cannot be proven. Do not blindly retry; inspect and reconcile.', 'WARNING', 'Uncertain external outcome')}<p><a href="${e(`${base}/automations`)}">Existing Automations reconciliation view</a>.</p>${notice('Governance audit gap: The domain mutation committed, but the normal dashboard audit write was not confirmed. Do not repeat the mutation. Gaps are not failed domain mutations.', 'WARNING', 'Committed mutation; audit unconfirmed')}<p><a href="${e(`${base}/data-retention`)}">Existing Data Retention governance</a> · <a href="${e(`${base}/privacy`)}">Existing Privacy governance</a>. Those guarded workflows remain authoritative.</p><p>Operations never retries, repairs, restarts, clears evidence, executes privacy requests or performs retention. Refresh with a normal GET.</p></section>
<section class="panel"><h2>Explicit not-tracked boundaries</h2>${notice('NOT_TRACKED is unknown, not zero or healthy.', 'WARNING', 'Explicit not-tracked boundaries')}${table('No durable proof in Eiren', ['Boundary', 'State'], guild.diagnostics.filter(d => d.status === 'NOT_TRACKED').map(d => [`${boundaryLabels[d.key] ?? d.key} (${d.key})`, 'NOT_TRACKED']))}<p>Database-backed sessions and fresh Discord authorization are required for this page. During dependency outages it may not render; use /healthz, /readyz and sanitized process logs. Synthetic restore rehearsal does not prove production backup availability.</p></section>`;
}
