import { escapeHtml } from './ui.js';
import { DENIAL_CODES, SCOPE_WARNING, WORKFLOW_EVIDENCE_WARNING, type AuditGapView, type InventorySummary, type PreviewView, type ReceiptView, type SubjectRequestView } from '../modules/subject-requests/contracts.js';

export type PrivacyInspection = { request: SubjectRequestView; inventory: InventorySummary; preview: PreviewView | null; receipt: ReceiptView | null; workflowEvidence: string; auditGaps: AuditGapView[] };
export type PrivacyDashboardView = { requests: SubjectRequestView[]; receipts: ReceiptView[]; selected: PrivacyInspection | null };
const safe = (value: unknown): string => escapeHtml(String(value ?? '—').slice(0, 1_500));
const fields = (rows: Array<[string, unknown]>): string => `<dl>${rows.map(([label, value]) => `<dt>${safe(label)}</dt><dd>${safe(value)}</dd>`).join('')}</dl>`;
function inventory(value: InventorySummary): string {
  return `${fields([['Eligible total', value.eligibleTotal], ['Retained total', value.retainedTotal]])}<div class="table-wrap"><table><thead><tr><th>Category / retained code</th><th>Disposition</th><th>Count</th></tr></thead><tbody>${value.counts.slice(0, 50).map(row => `<tr><td>${safe(row.category)}</td><td>${safe(row.disposition)}</td><td>${safe(row.count)}</td></tr>`).join('')}</tbody></table></div>`;
}
function receipt(value: ReceiptView): string {
  return fields([['Request ID', value.requestId], ['Outcome', value.outcome], ['Executed at', value.executedAt], ['Confirmed by', value.confirmedBy], ['Executed by', value.executedBy], ['Request version', value.requestVersion], ['Inventory hash', value.inventoryHash], ['Deleted member levels', value.deleted.memberLevels], ['Deleted reputation aggregates', value.deleted.memberReputation], ['Deleted achievements', value.deleted.achievements], ['Deleted event participants', value.deleted.eventParticipants], ['Deleted event attendance', value.deleted.eventAttendance], ['Retained total', value.retainedTotal]]);
}
export function renderPrivacyDashboard(guildId: string, csrfToken: string, view: PrivacyDashboardView, owner: boolean): string {
  const base = `/g/${encodeURIComponent(guildId)}/privacy`;
  const requests = view.requests.filter(r => r.guildId === guildId).slice(0, 50).map(r => `<tr><td><a href="${safe(`${base}?requestId=${encodeURIComponent(r.id)}`)}">${safe(r.id)}</a></td><td>${safe(r.subjectUserId)}</td><td>${safe(r.status)}</td><td>${safe(r.verificationMethod)}</td><td>${safe(r.subjectVerifiedAt)}</td><td>${safe(r.version)}</td></tr>`).join('');
  const receipts = view.receipts.filter(r => r.guildId === guildId).slice(0, 50).map(r => `<section><h3>Receipt ${safe(r.requestId)}</h3>${receipt(r)}</section>`).join('');
  let selected = '';
  const detail = view.selected;
  if (detail && detail.request.guildId === guildId) {
    const r = detail.request;
    const form = (action: string, label: string, phrase?: string, extra = '') => action === 'privacy-deny' && !canDeny ? '' : `<form method="post" action="${safe(`/g/${encodeURIComponent(guildId)}/action/${action}`)}"><h3>${safe(label)}</h3><input type="hidden" name="csrfToken" value="${safe(csrfToken)}"><input type="hidden" name="requestId" value="${safe(r.id)}">${extra}${phrase ? `<label class="check"><input type="checkbox" name="confirm" value="yes" required> I confirm this action</label><label>Type ${safe(phrase)}<input name="phrase" maxlength="40" required></label>` : ''}<button type="submit">${safe(label)}</button></form>`;
    const preview = detail.preview;
    const previewId = preview ? `<input type="hidden" name="previewId" value="${safe(preview.id)}">` : '';
    const canPreview = r.status === 'PENDING' || r.status === 'PREVIEWED';
    const canConfirm = owner && r.status === 'PREVIEWED' && !!preview;
    const canExecute = owner && r.status === 'CONFIRMED' && !!preview;
    const canDeny = owner && ['PENDING', 'PREVIEWED', 'CONFIRMED'].includes(r.status);
    selected = `<section><h2>Selected request</h2>${fields([['Request ID', r.id], ['Subject ID', r.subjectUserId], ['Status', r.status], ['Version', r.version], ['Verification method', r.verificationMethod], ['Verified at', r.subjectVerifiedAt], ['Requested at', r.requestedAt], ['Confirmed by', r.confirmedBy], ['Confirmed at', r.confirmedAt], ['Denied by', r.deniedBy], ['Denied at', r.deniedAt], ['Denial code', r.denialCode]])}<h3>Current inventory</h3>${inventory(detail.inventory)}<p class="notice">${safe(WORKFLOW_EVIDENCE_WARNING)}</p><p>${safe(detail.workflowEvidence)}</p>${preview ? `<section><h3>Preview</h3>${fields([['Preview ID', preview.id], ['Reviewed by', preview.reviewedBy], ['Created at', preview.createdAt], ['Expires at', preview.expiresAt], ['Consumed at', preview.consumedAt], ['Request version', preview.requestVersion], ['Inventory hash', preview.hash]])}${inventory(preview)}</section>` : '<p>No preview.</p>'}${detail.receipt ? `<section><h3>Execution receipt</h3>${receipt(detail.receipt)}</section>` : '<p>No execution receipt.</p>'}<section><h3>Audit persistence gaps (up to 50)</h3><div class="table-wrap"><table><thead><tr><th>Action</th><th>Actor</th><th>Target type</th><th>Target ID</th><th>Committed at</th><th>Detected at</th></tr></thead><tbody>${detail.auditGaps.slice(0, 50).map(g => `<tr><td>${safe(g.action)}</td><td>${safe(g.actorUserId)}</td><td>${safe(g.targetType)}</td><td>${safe(g.targetId)}</td><td>${safe(g.committedAt)}</td><td>${safe(g.detectedAt)}</td></tr>`).join('')}</tbody></table></div></section>${canPreview ? form('privacy-preview', r.status === 'PREVIEWED' ? 'Refresh preview' : 'Preview request') : ''}${owner ? `${canConfirm ? form('privacy-confirm', 'Confirm request', 'CONFIRM PRIVACY REQUEST', previewId) : ''}${canExecute ? form('privacy-execute', 'Erase eligible data', 'ERASE ELIGIBLE DATA', previewId) : ''}${form('privacy-deny', 'Deny request', 'DENY PRIVACY REQUEST', `<label>Denial code<select name="denialCode" required>${DENIAL_CODES.map(code => `<option value="${safe(code)}">${safe(code)}</option>`).join('')}</select></label>`)}` : '<p>Only the actual guild owner may confirm, execute or deny.</p>'}</section>`;
  }
  return `<p class="notice">${safe(SCOPE_WARNING)}</p><p>Requests originate from the subject’s authenticated guild interaction. There is no dashboard request creation or subject-ID input.</p><section><h2>Requests (up to 50)</h2><div class="table-wrap"><table><thead><tr><th>Request ID</th><th>Subject ID</th><th>Status</th><th>Verification</th><th>Verified at</th><th>Version</th></tr></thead><tbody>${requests}</tbody></table></div></section>${selected}<section><h2>Recent metadata receipts (up to 50)</h2>${receipts}</section>`;
}
