import { escapeHtml, statusBadge, notice, emptyState, fieldHelp, inputId, utc, panel, tableShell, formGroup } from './presentation.js';
import { DENIAL_CODES, SCOPE_WARNING, WORKFLOW_EVIDENCE_WARNING, type AuditGapView, type InventorySummary, type PreviewView, type ReceiptView, type SubjectRequestView } from '../modules/subject-requests/contracts.js';

export type PrivacyInspection = { request: SubjectRequestView; inventory: InventorySummary; preview: PreviewView | null; receipt: ReceiptView | null; workflowEvidence: string; auditGaps: AuditGapView[] };
export type PrivacyDashboardView = { requests: SubjectRequestView[]; receipts: ReceiptView[]; selected: PrivacyInspection | null };
const bounded = (value: unknown): string => String(value ?? '—').slice(0, 1_500);
const safe = (value: unknown): string => escapeHtml(bounded(value));
const fields = (rows: Array<[string, unknown]>): string => `<dl>${rows.map(([label, value]) => `<dt>${safe(label)}</dt><dd${/\bID\b| by$|hash$/i.test(label) ? ' class="id-value"' : ''}>${label === 'Status' || label === 'Outcome' ? statusBadge(bounded(value)) : safe(value)}</dd>`).join('')}</dl>`;
function inventory(value: InventorySummary): string {
  const selectedCounts = value.counts.slice(0, 50);
  return `${fields([['Eligible total (erase eligible)', value.eligibleTotal], ['Retained total', value.retainedTotal]])}${(['ERASE', 'RETAIN'] as const).map(disposition => {
    const rows = selectedCounts.filter(row => row.disposition === disposition);
    const title = disposition === 'ERASE' ? 'Erase eligible categories' : 'Retained categories';
    return `<h4>${title}</h4>${tableShell(title, ['Category / retained code', 'Disposition', 'Count'], rows.map(row => [bounded(row.category), bounded(row.disposition), row.count]))}${!rows.length ? emptyState(`No ${disposition === 'ERASE' ? 'erase eligible' : 'retained'} categories listed.`, 'This bounded inventory shows the selected request only.') : ''}`;
  }).join('')}`;
}
function receipt(value: ReceiptView): string {
  return fields([['Request ID', value.requestId], ['Outcome', value.outcome], ['Executed at UTC', utc(value.executedAt)], ['Confirmed by', value.confirmedBy], ['Executed by', value.executedBy], ['Request version', value.requestVersion], ['Inventory hash', value.inventoryHash], ['Deleted member levels', value.deleted.memberLevels], ['Deleted reputation aggregates', value.deleted.memberReputation], ['Deleted achievements', value.deleted.achievements], ['Deleted event participants', value.deleted.eventParticipants], ['Deleted event attendance', value.deleted.eventAttendance], ['Retained total', value.retainedTotal]]);
}
export function renderPrivacyDashboard(guildId: string, csrfToken: string, view: PrivacyDashboardView, owner: boolean): string {
  const base = `/g/${encodeURIComponent(guildId)}/privacy`;
  const requests = view.requests.filter(r => r.guildId === guildId).slice(0, 50).map(r => `<tr><td class="id-value"><a href="${safe(`${base}?requestId=${encodeURIComponent(r.id)}`)}">${safe(r.id)}</a></td><td class="id-value">${safe(r.subjectUserId)}</td><td>${statusBadge(bounded(r.status))}</td><td>${safe(r.verificationMethod)}</td><td>${safe(utc(r.subjectVerifiedAt))}</td><td>${safe(r.version)}</td></tr>`).join('');
  const receipts = view.receipts.filter(r => r.guildId === guildId).slice(0, 50).map(r => `<section class="panel"><h3>Receipt <span class="id-value">${safe(r.requestId)}</span></h3>${receipt(r)}</section>`).join('');
  let selected = '';
  const detail = view.selected;
  if (detail && detail.request.guildId === guildId) {
    const r = detail.request;
    const preview = detail.preview;
    const previewId = preview ? `<input type="hidden" name="previewId" value="${safe(preview.id)}">` : '';
    const canPreview = r.status === 'PENDING' || r.status === 'PREVIEWED';
    const canConfirm = owner && r.status === 'PREVIEWED' && !!preview;
    const canExecute = owner && r.status === 'CONFIRMED' && !!preview;
    const canDeny = owner && ['PENDING', 'PREVIEWED', 'CONFIRMED'].includes(r.status);
    const control = (action: string, name: string, label: string, html: (id: string, helpId: string) => string, help: string) => {
      const scope = `${action}-${r.id}`;
      const id = inputId(scope, name);
      const helpId = inputId(scope, `${name}-help`);
      return formGroup(label, html(id, helpId), fieldHelp(helpId, help));
    };
    const form = (action: string, label: string, phrase?: string, extra = '') => action === 'privacy-deny' && !canDeny ? '' : `<form class="panel" method="post" action="${safe(`/g/${encodeURIComponent(guildId)}/action/${action}`)}"><h3>${safe(label)}</h3>${phrase ? notice(action === 'privacy-execute' ? 'Execution erases only the reviewed, point-in-time eligible data. Retained accountability and external copies remain; future activity may recreate data.' : action === 'privacy-confirm' ? 'Confirmation binds the reviewed preview. It does not execute erasure; verify the eligible and retained categories.' : 'Denial records a terminal request decision. It does not execute eligible erasure.', 'WARNING', 'Review consequences') : ''}<input type="hidden" name="csrfToken" value="${safe(csrfToken)}"><input type="hidden" name="requestId" value="${safe(r.id)}">${extra}${phrase ? control(action, 'confirm', 'I confirm this action', (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" type="checkbox" name="confirm" value="yes" required>`, 'Required confirmation for this action.') + control(action, 'phrase', `Type ${phrase}`, (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" name="phrase" maxlength="40" required>`, `Enter ${phrase} exactly.`) : ''}<div class="action-group"><button class="${phrase ? 'btn-danger' : 'btn-primary'}" type="submit">${safe(label)}</button></div></form>`;
    const gaps = detail.auditGaps.slice(0, 50);
    selected = panel('Selected request', fields([['Request ID', r.id], ['Subject ID', r.subjectUserId], ['Status', r.status], ['Version', r.version], ['Verification method', r.verificationMethod], ['Verified at UTC', utc(r.subjectVerifiedAt)], ['Requested at UTC', utc(r.requestedAt)], ['Confirmed by', r.confirmedBy], ['Confirmed at UTC', utc(r.confirmedAt)], ['Denied by', r.deniedBy], ['Denied at UTC', utc(r.deniedAt)], ['Denial code', r.denialCode]]) + `<h3>Current inventory</h3>${inventory(detail.inventory)}` + notice(WORKFLOW_EVIDENCE_WARNING, 'WARNING', 'Retained workflow evidence') + `<p>${safe(detail.workflowEvidence)}</p>` + (preview ? `<section class="panel"><h3>Preview</h3>${fields([['Preview ID', preview.id], ['Reviewed by', preview.reviewedBy], ['Created at UTC', utc(preview.createdAt)], ['Expires at UTC', utc(preview.expiresAt)], ['Consumed at UTC', utc(preview.consumedAt)], ['Request version', preview.requestVersion], ['Inventory hash', preview.hash]])}${inventory(preview)}</section>` : emptyState('No preview.', 'No point-in-time preview is selected for this request.')) + (detail.receipt ? `<section class="panel"><h3>Execution receipt</h3>${receipt(detail.receipt)}</section>` : emptyState('No execution receipt.', 'No completed execution receipt is selected for this request.')) + `<section class="panel"><h3>Audit persistence gaps (up to 50)</h3>${gaps.length ? notice('The domain mutation committed, but the normal dashboard audit write was not confirmed. Do not repeat the mutation. Gaps are not failed domain mutations.', 'WARNING', 'Committed mutation; audit unconfirmed') : ''}${tableShell('Selected request audit persistence gaps', ['Action', 'Actor', 'Target type', 'Target ID', 'Committed at UTC', 'Detected at UTC'], gaps.map(g => [bounded(g.action), bounded(g.actorUserId), bounded(g.targetType), bounded(g.targetId), utc(g.committedAt), utc(g.detectedAt)]), { idColumns: [1, 3] })}${!gaps.length ? emptyState('No audit persistence gaps listed.', 'No gaps are recorded in this selected view.') : ''}</section>` + (canPreview ? form('privacy-preview', r.status === 'PREVIEWED' ? 'Refresh preview' : 'Preview request') : '') + (owner ? `${canConfirm ? form('privacy-confirm', 'Confirm request', 'CONFIRM PRIVACY REQUEST', previewId) : ''}${canExecute ? form('privacy-execute', 'Erase eligible data', 'ERASE ELIGIBLE DATA', previewId) : ''}${form('privacy-deny', 'Deny request', 'DENY PRIVACY REQUEST', control('privacy-deny', 'denialCode', 'Denial code', (id, helpId) => `<select id="${safe(id)}" aria-describedby="${safe(helpId)}" name="denialCode" required>${DENIAL_CODES.map(code => `<option value="${safe(code)}">${safe(code)}</option>`).join('')}</select>`, 'Select the existing reason for denying this request.'))}` : '<p>Only the actual guild owner may confirm, execute or deny.</p>'));
  }
  return notice(SCOPE_WARNING, 'WARNING', 'Point-in-time, guild-only scope') + `<p>Requests originate from the subject’s authenticated guild interaction. There is no dashboard request creation or subject-ID input. Eligible erasure is limited; retained accountability records remain. External copies and historical backups may remain.</p>` + panel('Requests (up to 50)', `<div class="table-wrap" role="region" aria-label="Privacy requests" tabindex="0"><table><caption>Selected-guild privacy requests</caption><thead><tr><th scope="col">Request ID</th><th scope="col">Subject ID</th><th scope="col">Status</th><th scope="col">Verification</th><th scope="col">Verified at UTC</th><th scope="col">Version</th></tr></thead><tbody>${requests}</tbody></table></div>${!requests ? emptyState('No privacy requests listed.', 'This view shows authenticated subject requests for the selected guild only.') : ''}`) + selected + panel('Recent metadata receipts (up to 50)', receipts || emptyState('No recent metadata receipts.', 'No execution receipts are listed for the selected guild.'));
}
