import { escapeHtml } from './ui.js';

export type RetentionView = {
  policy: { enabled: boolean; ticketDays: number; reportDays: number; appealDays: number; version: number; confirmedBy: string | null; confirmedAt: Date | string | null };
  eligibleCounts: { ticket: number; report: number; appeal: number };
  holdCounts: { ticket: number; report: number; appeal: number };
  activeHolds: Array<{ domain: string; recordId: number; heldBy: string | null; heldAt: Date | string | null }>;
  recentReceipts: Array<{ guildId: string; domain: string; recordId: number; policyVersion: number; redactedAt: Date | string }>;
};
export type RetentionPreview = { id: string; guildId: string; requestedBy: string; ticketDays: number; reportDays: number; appealDays: number; eligibleCounts: { ticket: number; report: number; appeal: number }; baseVersion: number; createdAt: Date | string; expiresAt: Date | string };
const safe = (value: unknown): string => escapeHtml(value instanceof Date ? value.toISOString() : value);
export function renderRetentionDashboard(guildId: string, csrfToken: string, view: RetentionView, preview: RetentionPreview | null, owner: boolean): string {
  const action = (name: string) => `/g/${encodeURIComponent(guildId)}/action/${name}`;
  const hidden = `<input type="hidden" name="csrfToken" value="${safe(csrfToken)}">`;
  const check = '<label class="check"><input type="checkbox" name="confirm" value="yes" required> I confirm this action</label>';
  const counts = (value: RetentionView['eligibleCounts']) => `<ul><li>Tickets: ${safe(value.ticket)}</li><li>Reports: ${safe(value.report)}</li><li>Appeals: ${safe(value.appeal)}</li></ul>`;
  const p = view.policy;
  const holds = view.activeHolds.slice(0, 50).map(h => `<tr><td>${safe(h.domain)}</td><td>${safe(h.recordId)}</td><td>${safe(h.heldBy ?? '—')}</td><td>${safe(h.heldAt ?? '—')}</td></tr>`).join('');
  const receipts = view.recentReceipts.slice(0, 50).filter(r => r.guildId === guildId).map(r => `<tr><td>${safe(r.domain)}</td><td>${safe(r.recordId)}</td><td>${safe(r.policyVersion)}</td><td>${safe(r.redactedAt)}</td></tr>`).join('');
  return `<p class="notice">DB-only retention: this policy redacts database records only. Discord messages, exports, backups and other copies are not removed. Private narratives are never displayed here.</p><section><h2>Policy</h2><dl><dt>Enabled</dt><dd>${safe(p.enabled)}</dd><dt>Ticket days</dt><dd>${safe(p.ticketDays)}</dd><dt>Report days</dt><dd>${safe(p.reportDays)}</dd><dt>Appeal days</dt><dd>${safe(p.appealDays)}</dd><dt>Version</dt><dd>${safe(p.version)}</dd><dt>Confirmed by</dt><dd>${safe(p.confirmedBy ?? '—')}</dd><dt>Confirmed at</dt><dd>${safe(p.confirmedAt ?? '—')}</dd></dl></section><section><h2>Eligible counts</h2>${counts(view.eligibleCounts)}<h2>Hold counts</h2>${counts(view.holdCounts)}</section><section><h2>Active holds (up to 50)</h2><div class="table-wrap"><table><thead><tr><th>Domain</th><th>Record ID</th><th>Held by</th><th>Held at</th></tr></thead><tbody>${holds}</tbody></table></div></section><section><h2>Recent redaction receipts</h2><div class="table-wrap"><table><thead><tr><th>Domain</th><th>Record ID</th><th>Policy version</th><th>Redacted at</th></tr></thead><tbody>${receipts}</tbody></table></div></section>${owner ? `<form method="post" action="${action('retention-preview')}"><h2>Preview retention policy</h2>${hidden}${(['ticket', 'report', 'appeal'] as const).map(d => `<label>${d} days<input type="number" name="${d}Days" min="${d === 'ticket' ? 30 : 90}" max="${d === 'ticket' ? 365 : 730}" step="1" required></label>`).join('')}<button type="submit">Preview</button></form>${preview ? `<section><h2>Pending preview</h2><p>Preview ID: ${safe(preview.id)} · Base version: ${safe(preview.baseVersion)} · Expires: ${safe(preview.expiresAt)}</p><p>Windows: tickets ${safe(preview.ticketDays)}, reports ${safe(preview.reportDays)}, appeals ${safe(preview.appealDays)} days.</p><h3>Eligible at preview</h3>${counts(preview.eligibleCounts)}<form method="post" action="${action('retention-confirm')}"><h3>Enable or change policy</h3>${hidden}<input type="hidden" name="previewId" value="${safe(preview.id)}">${check}<label>Type ENABLE RETENTION<input type="text" name="phrase" maxlength="16" required></label><button type="submit">Confirm policy</button></form></section>` : ''}<form method="post" action="${action('retention-disable')}"><h2>Disable retention</h2>${hidden}${check}<button type="submit">Disable</button></form>${(['set', 'clear'] as const).map(op => `<form method="post" action="${action(`retention-hold-${op}`)}"><h2>${op === 'set' ? 'Set' : 'Clear'} legal hold</h2>${hidden}<label>Domain<select name="domain"><option>TICKET</option><option>REPORT</option><option>APPEAL</option></select></label><label>Record ID<input type="number" name="recordId" min="1" step="1" required></label>${check}<button type="submit">${op === 'set' ? 'Set' : 'Clear'} hold</button></form>`).join('')}` : ''}`;
}
