import { escapeHtml, statusBadge, notice, emptyState, fieldHelp, inputId, utc, panel, metadataList, tableShell, formGroup } from './presentation.js';

export type RetentionView = {
  policy: { enabled: boolean; ticketDays: number; reportDays: number; appealDays: number; version: number; confirmedBy: string | null; confirmedAt: Date | string | null };
  eligibleCounts: { ticket: number; report: number; appeal: number };
  holdCounts: { ticket: number; report: number; appeal: number };
  activeHolds: Array<{ domain: string; recordId: number; heldBy: string | null; heldAt: Date | string | null }>;
  recentReceipts: Array<{ guildId: string; domain: string; recordId: number; policyVersion: number; redactedAt: Date | string }>;
};
export type RetentionPreview = { id: string; guildId: string; requestedBy: string; ticketDays: number; reportDays: number; appealDays: number; eligibleCounts: { ticket: number; report: number; appeal: number }; baseVersion: number; createdAt: Date | string; expiresAt: Date | string };
const safe = escapeHtml;
export function renderRetentionDashboard(guildId: string, csrfToken: string, view: RetentionView, preview: RetentionPreview | null, owner: boolean): string {
  const action = (name: string) => `/g/${encodeURIComponent(guildId)}/action/${name}`;
  const hidden = `<input type="hidden" name="csrfToken" value="${safe(csrfToken)}">`;
  const scope = (name: string) => `retention-${guildId}-${name}`;
  const control = (actionName: string, name: string, label: string, html: (id: string, helpId: string) => string, help: string) => {
    const id = inputId(scope(actionName), name);
    const helpId = inputId(scope(actionName), `${name}-help`);
    return formGroup(label, html(id, helpId), fieldHelp(helpId, help));
  };
  const check = (name: string) => control(name, 'confirm', 'I confirm this action', (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" type="checkbox" name="confirm" value="yes" required>`, 'Required confirmation for this action.');
  const counts = (value: RetentionView['eligibleCounts']) => metadataList([['Tickets', value.ticket], ['Reports', value.report], ['Appeals', value.appeal]]);
  const p = view.policy;
  const holds = view.activeHolds.slice(0, 50);
  const receipts = view.recentReceipts.slice(0, 50).filter(r => r.guildId === guildId);
  const policy = panel('Policy', `<p>State: ${statusBadge(p.enabled ? 'Enabled' : 'Disabled')}</p>${metadataList([['Ticket days', p.ticketDays], ['Report days', p.reportDays], ['Appeal days', p.appealDays], ['Version', p.version], ['Confirmed by', p.confirmedBy ?? '—'], ['Confirmed at UTC', utc(p.confirmedAt)]])}`);
  const tables = panel('Active holds (up to 50)', tableShell('Records retained under legal hold', ['Domain', 'Record ID', 'Held by', 'Held at UTC'], holds.map(h => [h.domain, h.recordId, h.heldBy ?? '—', utc(h.heldAt)]), { idColumns: [1, 2] }) + (!holds.length ? emptyState('No active holds.', 'No legal holds are listed in this selected view.') : '')) + panel('Recent redaction receipts', tableShell('Up to 50 selected-guild redaction receipts', ['Domain', 'Record ID', 'Policy version', 'Redacted at UTC'], receipts.map(r => [r.domain, r.recordId, r.policyVersion, utc(r.redactedAt)]), { idColumns: [1] }) + (!receipts.length ? emptyState('No recent redaction receipts.', 'No database redactions are listed in this selected view.') : ''));
  const form = (name: string, title: string, body: string, button: string, danger = false) => `<form class="panel" method="post" action="${safe(action(name))}"><h2>${safe(title)}</h2>${danger ? notice(name === 'retention-confirm' ? 'Enabling or changing this policy may redact eligible database records. Review the preview windows; external copies and historical backups are not removed.' : name === 'retention-disable' ? 'Disabling the policy does not restore already-redacted content.' : 'Clearing this legal hold may make the selected record eligible for existing retention processing.', 'WARNING', 'Review consequences') : ''}${hidden}${body}<div class="action-group"><button class="${danger ? 'btn-danger' : 'btn-primary'}" type="submit">${safe(button)}</button></div></form>`;
  const ownerForms = !owner ? '' : form('retention-preview', 'Preview retention policy', (['ticket', 'report', 'appeal'] as const).map(d => control('preview', `${d}Days`, `${d} days`, (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" type="number" name="${d}Days" min="${d === 'ticket' ? 30 : 90}" max="${d === 'ticket' ? 365 : 730}" step="1" required>`, `Allowed window: ${d === 'ticket' ? '30–365' : '90–730'} days.`)).join(''), 'Preview') + (preview ? panel('Pending preview', metadataList([['Preview ID', preview.id], ['Base version', preview.baseVersion], ['Expires UTC', utc(preview.expiresAt)]]) + `<p>Windows: tickets ${safe(preview.ticketDays)}, reports ${safe(preview.reportDays)}, appeals ${safe(preview.appealDays)} days.</p><h3>Eligible at preview</h3>${counts(preview.eligibleCounts)}` + form('retention-confirm', 'Enable or change policy', `<input type="hidden" name="previewId" value="${safe(preview.id)}">${check('confirm')}` + control('confirm', 'phrase', 'Type ENABLE RETENTION', (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" type="text" name="phrase" maxlength="16" required>`, 'Enter ENABLE RETENTION exactly.'), 'Confirm policy', true)) : '') + form('retention-disable', 'Disable retention', check('disable'), 'Disable', true) + (['set', 'clear'] as const).map(op => form(`retention-hold-${op}`, `${op === 'set' ? 'Set' : 'Clear'} legal hold`, control(`hold-${op}`, 'domain', 'Domain', (id, helpId) => `<select id="${safe(id)}" aria-describedby="${safe(helpId)}" name="domain"><option>TICKET</option><option>REPORT</option><option>APPEAL</option></select>`, 'Select the existing record domain.') + control(`hold-${op}`, 'recordId', 'Record ID', (id, helpId) => `<input id="${safe(id)}" aria-describedby="${safe(helpId)}" type="number" name="recordId" min="1" step="1" required>`, 'Use the existing record ID in the selected domain.') + check(`hold-${op}`), `${op === 'set' ? 'Set' : 'Clear'} hold`, op === 'clear')).join('');
  return notice('DB-only retention: this policy redacts database records only. Discord copies/messages, downloaded exports, screenshots, historical backups and other external copies are not removed. Private narratives are never displayed here.', 'WARNING', 'Database-only redaction') + policy + panel('Eligible counts', counts(view.eligibleCounts)) + panel('Hold counts — retained', counts(view.holdCounts)) + tables + ownerForms;
}
