import { renderAutomationDashboard, type AutomationDashboardView } from './automation-ui.js';
import { renderRetentionDashboard, type RetentionView, type RetentionPreview } from './retention-ui.js';
import { renderPrivacyDashboard, type PrivacyDashboardView } from './privacy-ui.js';
import { renderOperationsDashboard } from './operations-ui.js';
import type { OperationsDashboardView } from '../services/operations-view.js';
import { escapeHtml, statusBadge, notice as renderNotice, emptyState, pageHeader, metadataList, tableShell, formGroup, fieldHelp, inputId, destructiveWarning, utc } from './presentation.js';
export { escapeHtml } from './presentation.js';
import { brandMark, emptyArt } from './brand.js';
import { dashboardTheme } from './theme.js';

type PageInput = { page: string; guildId: string; guildName: string; csrfToken: string; items?: unknown; data?: unknown; notice?: string; analyticsEnabled?: boolean; disabledModule?: string; actorLevel?: string; range?: string; userId?: string; retentionPreview?: RetentionPreview | null; isGuildOwner?: boolean };
const pages = [ ['overview', 'Overview'], ['moderation', 'Moderation'], ['members', 'Members'], ['roles', 'Roles'], ['tickets', 'Tickets'], ['suggestions', 'Suggestions'], ['levels', 'Levels'], ['events', 'Events'], ['giveaways', 'Giveaways'], ['analytics', 'Analytics'], ['automations', 'Automations'], ['data-retention', 'Data retention'], ['privacy', 'Privacy requests'], ['operations', 'Operations'], ['settings', 'Bot Settings'] ] as const;
const groups = [ ['General', ['overview', 'members']], ['Moderation', ['moderation', 'tickets', 'suggestions', 'roles']], ['Community', ['levels', 'events', 'giveaways', 'analytics']], ['Automation', ['automations']], ['Governance', ['data-retention', 'privacy', 'operations']], ['System', ['settings']] ] as const;
const descriptions: Record<string, string> = { overview: 'Current server counts and recorded configuration. No inferred trends.', moderation: 'Case and report metadata, with existing guarded staff actions.', members: 'Look up a current server member using their Discord ID.', roles: 'Role menus and owner-controlled permission mappings.', tickets: 'Ticket lifecycle metadata and existing staff close controls.', suggestions: 'Suggestions and their current review status.', levels: 'Member levels and existing configuration.', events: 'Event lifecycle and participant summaries.', giveaways: 'Giveaway lifecycle and eligibility summaries.', analytics: 'Existing server analytics. Table timestamps are UTC; configured timezone is a label.', automations: 'Scheduled rules, execution evidence and guarded reconciliation.', 'data-retention': 'Database-only policy and accountable redaction evidence.', privacy: 'Point-in-time requests: limited eligible erasure and retained accountability.', operations: 'Read-only operational evidence. Runtime telemetry is since process restart.', settings: 'Existing module availability and server settings.' };
const levels = ['MEMBER', 'HELPER', 'MODERATOR', 'SENIOR_MODERATOR', 'ADMIN', 'GUILD_OWNER', 'BOT_OWNER'];
const may = (actor: string | undefined, required: string): boolean => actor !== undefined && levels.indexOf(actor) >= levels.indexOf(required);
const path = (guildId: string): string => `/g/${encodeURIComponent(guildId)}`;
const logout = (csrfToken?: string): string => csrfToken === undefined ? '' : `<form method="post" action="/logout" class="logout"><input type="hidden" name="csrfToken" value="${escapeHtml(csrfToken)}"><button class="btn-subtle" type="submit">Log out</button></form>`;
const layout = (title: string, body: string, nav = '', csrfToken?: string, context?: { guildName: string; actorLevel?: string }): string => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} · Eiren Dashboard</title><link rel="stylesheet" href="/assets/dashboard.css"></head><body class="${nav ? 'has-nav' : 'public-page'}"><a class="skip" href="#main">Skip to content</a><header class="top"><a class="brand" href="/guilds">${brandMark}<span>Eiren</span></a><div class="header-context"><span>${escapeHtml(context?.guildName ?? title)}</span>${context?.actorLevel ? `<small class="muted">Access level: ${escapeHtml(context.actorLevel)}</small>` : ''}</div>${logout(csrfToken)}</header>${nav}<main id="main" tabindex="-1">${body}</main><footer>Eiren · Administration dashboard</footer></body></html>`;

export function renderLogin(error?: string): string {
  return layout('Sign in', `<section class="panel auth-panel login-panel"><div class="login-identity">${brandMark}<span>Eiren</span></div>${pageHeader('Sign in', 'Use Discord to manage servers you currently have access to.')}${error ? renderNotice(error, 'DANGER', 'Sign-in failed') : ''}<a class="button btn-primary" href="/auth/discord">Continue with Discord</a><p class="muted">Current server membership and Eiren permissions are checked before access.</p></section>`);
}
export function renderGuildPicker(guilds: Array<{ id: string; name: string }>, csrfToken?: string): string {
  const entries = guilds.slice(0, 100).map(({ id, name }) => `<li><a href="${escapeHtml(`${path(String(id))}/overview`)}"><strong>${escapeHtml(name)}</strong><span class="muted">Open dashboard</span></a></li>`).join('');
  return layout('Choose a server', `<section class="panel auth-panel">${pageHeader('Choose a server', 'Select a server to view its administration dashboard.')}${guilds.length ? `<ul class="guild-list">${entries}</ul>` : `<div class="illustrated-empty">${emptyArt}${emptyState('No manageable servers are available.', 'Access is based on current membership and Eiren permissions.')}</div>`}${guilds.length > 100 ? '<p class="muted">Only the first 100 servers are shown.</p>' : ''}</section>`, '', csrfToken);
}
const protectedKey = /(?:secret|token|password|authorization|credential|private|transcript|reporttext|appealtext|supporttext|messagecontent|content|body|email|phone|ipaddress|webhook|oauth|cookie|sessionhash)/i;
const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value) && !(value instanceof Date);
const readable = (value: unknown): string => value instanceof Date ? utc(value) : typeof value === 'string' ? value : typeof value === 'number' || typeof value === 'boolean' ? String(value) : '—';
const label = (key: string) => key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, c => c.toUpperCase());
const emptyLabels: Record<string, string> = { Tickets: 'No tickets to display.', Giveaways: 'No giveaways to display.', Events: 'No events to display.', Moderation: 'No case or report metadata to display.', Members: 'No matching member records.', Suggestions: 'No suggestions to display.', Levels: 'No level records to display.', Analytics: 'No analytics records for this range.', Roles: 'No role configuration records to display.', 'Bot Settings': 'No saved settings to display.' };
function table(input: unknown, name: string, showSuggestionContent = false): string {
  if (!Array.isArray(input) || !input.length) return emptyState(emptyLabels[name] ?? `No ${name.toLowerCase()} records to display.`);
  const rows = input.slice(0, 100).filter(record);
  const columns = [...new Set(rows.flatMap(row => Object.keys(row)))].filter(key => (showSuggestionContent && key === 'content') || !protectedKey.test(key)).slice(0, 8);
  if (!rows.length || !columns.length) return emptyState('No public summary fields to display.');
  return `<p class="muted">${rows.length} record${rows.length === 1 ? '' : 's'} shown${input.length > 100 ? ' (first 100)' : ''}.</p>${tableShell(`Read-only summary: ${name} (up to 100 records)`, columns.map(label), rows.map(row => columns.map(key => readable(row[key]))), { statusColumns: columns.flatMap((key, i) => /^(status|enabled|.*Status)$/.test(key) ? [i] : []), idColumns: columns.flatMap((key, i) => /(^id$|Id$)/.test(key) ? [i] : []) })}`;
}
function sections(input: unknown, name: string, depth = 0): string {
  if (Array.isArray(input)) return table(input, name, name === 'Suggestions');
  if (!record(input)) return emptyState(emptyLabels[name] ?? `No ${name.toLowerCase()} records to display.`);
  return Object.entries(input).filter(([key]) => !protectedKey.test(key)).slice(0, 16).map(([key, value]) => {
    const title = label(key), heading = Math.min(depth + 2, 4);
    const body = Array.isArray(value) ? table(value, title) : record(value) && depth < 3 ? sections(value, title, depth + 1) : `<p>${escapeHtml(readable(value))}</p>`;
    return `<section class="data-section" aria-label="${escapeHtml(`${name} ${title}`)}"><h${heading}>${escapeHtml(title)}</h${heading}>${body}</section>`;
  }).join('') || emptyState('No public summary fields to display.');
}
function overview(input: unknown): string {
  if (!record(input) || !record(input.counts)) return sections(input, 'Overview');
  const metrics = [['activeCases', 'Active cases'], ['openReports', 'Open reports'], ['openTickets', 'Open tickets'], ['pendingSuggestions', 'Pending suggestions'], ['scheduledEvents', 'Scheduled events'], ['activeGiveaways', 'Active giveaways']] as const;
  return `<section aria-label="Current operational counts"><h2>Current summary</h2><dl class="metric-grid">${metrics.map(([key, title]) => `<div class="metric"><dt>${title}</dt><dd>${escapeHtml((input.counts as Record<string, unknown>)[key] ?? '—')}</dd></div>`).join('')}</dl></section>${record(input.identity) ? `<section><h2>Server metadata</h2>${metadataList([['Server ID', input.identity.id], ['Current members', input.identity.memberCount]])}</section>` : ''}${typeof input.analyticsEnabled === 'boolean' ? `<p>Analytics: ${statusBadge(input.analyticsEnabled)}</p>` : ''}${sections({ settings: input.settings, modules: input.modules }, 'Overview')}`;
}
export function renderPage({ page, guildId, guildName, csrfToken, items, data, notice, analyticsEnabled = false, disabledModule, actorLevel, range, userId, retentionPreview, isGuildOwner = false }: PageInput): string {
  const selected = pages.find(([key, title]) => key === page || title === page), key = selected?.[0], base = path(guildId);
  const visible = pages.filter(([route]) => !['automations', 'data-retention', 'privacy', 'operations'].includes(route) || may(actorLevel, 'ADMIN'));
  const navigation = `<nav class="side" aria-label="Dashboard"><a class="server-picker" href="/guilds">All servers</a><p class="nav-hint muted">On narrow screens, scroll navigation groups horizontally.</p><div class="nav-groups" tabindex="0" role="region" aria-label="Navigation groups">${groups.map(([group, routes]) => { const entries = visible.filter(([route]) => (routes as readonly string[]).includes(route)); return entries.length ? `<section class="nav-group"><h2>${group}</h2><ul>${entries.map(([route, title]) => `<li><a href="${escapeHtml(`${base}/${route}`)}"${key === route ? ' aria-current="page"' : ''}>${title}</a></li>`).join('')}</ul></section>` : ''; }).join('')}</div></nav>`;
  const helpText = (name: string): string | undefined => /Id$/.test(name) ? 'Use the existing Discord ID; no name or mention syntax.' : name === 'module' ? 'Use the registered module key. Disabling does not delete historical data.' : name === 'timezone' ? 'Use an IANA timezone, such as UTC or Europe/London.' : name === 'days' ? 'Whole days within the existing permitted range.' : undefined;
  let scope = key ?? 'page';
  const text = (name: string, title: string, max = 200, pattern = ''): string => {
    const id = inputId(scope, name), help = helpText(name);
    return formGroup(title, `<input id="${id}" name="${name}" type="text" maxlength="${max}"${pattern ? ` pattern="${pattern}"` : ''}${help ? ` aria-describedby="${id}-help"` : ''} required>`, help ? fieldHelp(`${id}-help`, help) : '');
  };
  const number = (name: string, title: string, min: number, max: number): string => { const id = inputId(scope, name), help = helpText(name); return formGroup(title, `<input id="${id}" name="${name}" type="number" min="${min}" max="${max}" step="1"${help ? ` aria-describedby="${id}-help"` : ''} required>`, help ? fieldHelp(`${id}-help`, help) : ''); };
  const choice = (name: string, title: string, options: readonly string[]): string => formGroup(title, `<select name="${name}" required>${options.map(option => `<option value="${escapeHtml(option)}">${escapeHtml(option)}</option>`).join('')}</select>`);
  const form = (action: string, title: string, fields: string, confirmation = false): string => {
    const dangerous = ['moderation-warn', 'ticket-close', 'event-cancel', 'giveaway-end', 'role-remove', 'analytics-retention'].includes(action);
    const consequences: Record<string, string> = { 'module-toggle': 'Disabling a module stops its activity; historical data is not deleted.', 'analytics-toggle': 'Disabling Analytics stops collection; historical data is not deleted.', 'role-set': 'Permission mappings change access to protected commands. Verify the role and permission level.', 'role-remove': 'Removing this mapping changes protected-command access for the selected role. Verify the role ID.', 'moderation-warn': 'This records a warning case for the selected member. Verify the member ID and reason.', 'ticket-close': 'This closes the selected ticket using its existing lifecycle. Verify the ticket ID and reason.', 'event-cancel': 'This cancels the selected event using its existing transition rules.', 'giveaway-end': 'This ends the selected giveaway using its existing completion flow.', 'analytics-retention': 'This changes how long Analytics records are retained. Existing cleanup policy applies.' };
    return `<form class="action-form" method="post" action="${escapeHtml(`${base}/action/${action}`)}"><h2>${escapeHtml(title)}</h2><input type="hidden" name="csrfToken" value="${escapeHtml(csrfToken)}">${confirmation ? destructiveWarning(consequences[action] ?? 'Verify the selected record and consequences before confirming.') : ''}${fields}${confirmation ? '<label class="check"><input type="checkbox" name="confirm" value="yes" required> I confirm this destructive action</label>' : ''}<button class="${dangerous ? 'btn-danger' : 'btn-primary'}" type="submit">${escapeHtml(title)}</button></form>`;
  };
  const forms: string[] = [];
  const add = (required: string, action: string, title: string, fields: () => string, confirmation = false) => { if (!disabledModule && may(actorLevel, required)) { scope = action; forms.push(form(action, title, fields(), confirmation)); } };
  if (key === 'settings') { add('ADMIN', 'module-toggle', 'Set module availability', () => text('module', 'Module key', 40, '[a-z][a-z0-9_-]*') + choice('enabled', 'Enabled', ['true', 'false']), true); add('ADMIN', 'guild-timezone', 'Set server timezone', () => text('timezone', 'IANA timezone', 64)); }
  if (key === 'moderation') add('MODERATOR', 'moderation-warn', 'Warn member', () => text('targetId', 'Member ID', 20, '[0-9]{17,20}') + text('reason', 'Reason', 400), true);
  if (key === 'tickets') add('MODERATOR', 'ticket-close', 'Close ticket', () => number('id', 'Ticket ID', 1, Number.MAX_SAFE_INTEGER) + text('reason', 'Reason', 400), true);
  if (key === 'suggestions') add('MODERATOR', 'suggestion-status', 'Update suggestion status', () => number('id', 'Suggestion ID', 1, Number.MAX_SAFE_INTEGER) + choice('status', 'Status', ['PENDING', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'IMPLEMENTED']));
  if (key === 'levels') add('ADMIN', 'levels-config', 'Set minimum message length', () => number('minLength', 'Minimum message length', 0, 2000));
  if (key === 'events') add('MODERATOR', 'event-cancel', 'Cancel event', () => number('id', 'Event ID', 1, Number.MAX_SAFE_INTEGER), true);
  if (key === 'giveaways') add('MODERATOR', 'giveaway-end', 'End giveaway', () => number('id', 'Giveaway ID', 1, Number.MAX_SAFE_INTEGER), true);
  if (key === 'analytics') { add('ADMIN', 'analytics-toggle', 'Set analytics availability', () => choice('enabled', 'Enabled', ['true', 'false']), true); add('ADMIN', 'analytics-retention', 'Set analytics retention', () => number('days', 'Retention days', 30, 730), true); }
  if (key === 'roles') { add('GUILD_OWNER', 'role-set', 'Set permission role', () => text('roleId', 'Role ID', 20, '[0-9]{17,20}') + choice('level', 'Permission level', ['HELPER', 'MODERATOR', 'SENIOR_MODERATOR', 'ADMIN']), true); add('GUILD_OWNER', 'role-remove', 'Remove permission role', () => text('roleId', 'Role ID', 20, '[0-9]{17,20}'), true); }
  const rangeSelector = key === 'analytics' ? `<form class="filter-form" method="get" action="${escapeHtml(`${base}/analytics`)}">${formGroup('Analytics range', `<select name="range">${(['24h', '7d', '30d', '90d'] as const).map(option => `<option value="${option}"${range === option ? ' selected' : ''}>${option}</option>`).join('')}</select>`)}<button class="btn-secondary" type="submit">Show range</button></form>` : '';
  const memberLookup = key === 'members' ? `<form class="filter-form" method="get" action="${escapeHtml(`${base}/members`)}">${formGroup('Member user ID', `<input type="text" name="userId" maxlength="20" pattern="[0-9]{17,20}" value="${escapeHtml(userId ?? '')}" aria-describedby="member-lookup-help" required>`, fieldHelp('member-lookup-help', 'Enter the Discord ID of a current server member.'))}<button class="btn-secondary" type="submit">Look up member</button></form>` : '';
  const source = items ?? data;
  const summary = key === 'operations' ? may(actorLevel, 'ADMIN') && data ? renderOperationsDashboard(guildId, data as OperationsDashboardView) : emptyState('Operations unavailable.') : key === 'privacy' ? may(actorLevel, 'ADMIN') && data ? renderPrivacyDashboard(guildId, csrfToken, data as PrivacyDashboardView, isGuildOwner) : emptyState('Privacy request service unavailable.') : key === 'data-retention' ? data ? renderRetentionDashboard(guildId, csrfToken, data as RetentionView, retentionPreview ?? null, isGuildOwner) : emptyState('Retention service unavailable.') : key === 'automations' ? may(actorLevel, 'ADMIN') && data ? renderAutomationDashboard({ guildId, csrfToken, data: data as AutomationDashboardView }) : renderNotice('This page is not available.', 'DANGER') : !key ? renderNotice('This page is not available.', 'DANGER') : disabledModule
    ? renderNotice(`${disabledModule} is disabled for this server. Historical data may still exist.`, 'NEUTRAL', 'Disabled') + statusBadge('DISABLED')
    : key === 'analytics' && !analyticsEnabled ? renderNotice('Analytics is disabled for this server. Historical data may still exist.', 'NEUTRAL') + statusBadge('DISABLED') : key === 'overview' ? overview(source) : sections(source, selected[1]);
  return layout(`${selected?.[1] ?? 'Page unavailable'} · ${guildName}`, `<div class="content">${pageHeader(selected?.[1] ?? 'Page unavailable', key ? descriptions[key] : undefined)}${notice ? renderNotice(notice, 'SUCCESS') : ''}${rangeSelector}${memberLookup}${summary}${forms.join('')}</div>`, navigation, csrfToken, { guildName, actorLevel });
}
export function dashboardCss(): string { return dashboardTheme; }
